//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace White.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdminDBEntities : DbContext
    {
        public AdminDBEntities()
            : base("name=AdminDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Error_Log> Error_Log { get; set; }
        public virtual DbSet<Functional> Functional { get; set; }
        public virtual DbSet<Resource> Resource { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<WX_Config> WX_Config { get; set; }
        public virtual DbSet<Action_Log> Action_Log { get; set; }
        public virtual DbSet<User_Info> User_Info { get; set; }
        public virtual DbSet<V_User_Info> V_User_Info { get; set; }
    }
}
