//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace White.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Info
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string BarePass { get; set; }
        public string Realname { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string UserAddress { get; set; }
        public string IpAddress { get; set; }
        public bool IsAdmin { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string Phone { get; set; }
        public string QQ { get; set; }
        public string WeChat { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public bool IsValid { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
    }
}
